<p> Cloud Chamber Particle Track Identifying Machine Learning Project </p>
<p> By Merrick Lavinsky </p>

In [7]:
#We first need to upload and split the video into its constituent frames
import numpy as np
import cv2

Vid = cv2.VideoCapture('CCTL_0m55s_newres.mp4')
#For initialization of previous frame
prevframeinc = 0
while(Vid.isOpened()):
    #Finding dimensions of the frames
    ret, frame = Vid.read()
    dimy = frame.shape[0]
    dimx = frame.shape[1]
    
    #Make a copy of the frame to edit
    new_frame = frame
    
    #Convert to gray scale since we do not need RBG
    
    Grey_frame = cv2.cvtColor(new_frame, cv2.COLOR_BGR2GRAY)
    #print(new_frame[400,0])
    if prevframeinc == 0:
        Diff_frame = Grey_frame
    else:
        Diff_frame = Grey_frame - Prev_frame
    
    #print(i)    
    No_Events = 0
    Events = 0
    
    for i in range(dimy):
        for j in range(dimx):
            pixelval = Diff_frame[i,j]
            if pixelval <= 50:
                Diff_frame[i,j] = 0
                No_Events = No_Events + 1
                
            else:
                Diff_frame[i,j] = pixelval
                Events = Events + 1
    
    #print(new_frame)
    print(No_Events, "non-changed pixels and", Events, "changed pixels")
    cv2.imshow('Diff_frame',Diff_frame)
    
    print("Current Frame")
    print(Grey_frame)
    
    if prevframeinc > 0:
        print("Previous Frame")
        print(Prev_frame)
    
    print("Difference of Frames")    
    print(Diff_frame)
    
    Prev_frame = Grey_frame
    prevframeinc = prevframeinc + 1
    
    
    if cv2.waitKey(100) & 0xFF == ord('q'):
        break
    

Vid.release()
cv2.destroyAllWindows()

0 non-changed pixels and 224992 changed pixels
Current Frame
[[171 171 168 ... 176 176 174]
 [172 171 170 ... 175 174 174]
 [179 172 171 ... 174 174 174]
 ...
 [172 173 173 ... 184 186 200]
 [173 173 173 ... 185 189 207]
 [173 173 173 ... 185 190 210]]
Difference of Frames
[[171 171 168 ... 176 176 174]
 [172 171 170 ... 175 174 174]
 [179 172 171 ... 174 174 174]
 ...
 [172 173 173 ... 184 186 200]
 [173 173 173 ... 185 189 207]
 [173 173 173 ... 185 190 210]]
224649 non-changed pixels and 343 changed pixels
Current Frame
[[178 178 175 ... 180 180 178]
 [179 179 177 ... 180 179 178]
 [186 179 177 ... 179 179 178]
 ...
 [180 180 180 ... 189 190 203]
 [180 180 180 ... 189 192 210]
 [180 180 180 ... 189 193 213]]
Previous Frame
[[171 171 168 ... 176 176 174]
 [172 171 170 ... 175 174 174]
 [179 172 171 ... 174 174 174]
 ...
 [172 173 173 ... 184 186 200]
 [173 173 173 ... 185 189 207]
 [173 173 173 ... 185 190 210]]
Difference of Frames
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0

218770 non-changed pixels and 6222 changed pixels
Current Frame
[[168 168 165 ... 172 172 171]
 [169 168 169 ... 171 170 171]
 [176 168 167 ... 170 171 171]
 ...
 [168 169 169 ... 180 183 191]
 [169 169 169 ... 180 186 197]
 [169 170 170 ... 181 186 198]]
Previous Frame
[[168 168 165 ... 172 172 171]
 [169 168 169 ... 171 170 171]
 [176 168 167 ... 170 171 171]
 ...
 [168 169 169 ... 180 182 192]
 [169 169 169 ... 180 185 198]
 [169 170 170 ... 181 185 199]]
Difference of Frames
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0 255]]
189592 non-changed pixels and 35400 changed pixels
Current Frame
[[168 168 165 ... 171 171 170]
 [169 168 169 ... 170 169 170]
 [176 168 167 ... 169 170 170]
 ...
 [168 169 169 ... 180 183 190]
 [169 169 169 ... 180 186 196]
 [169 170 170 ... 181 186 197]]
Previous Frame
[[168 168 165 ... 172 172 171]
 [169 168 169 ... 171

218554 non-changed pixels and 6438 changed pixels
Current Frame
[[168 168 165 ... 171 170 170]
 [169 168 169 ... 170 170 170]
 [176 169 168 ... 170 170 170]
 ...
 [169 168 168 ... 178 182 190]
 [168 170 170 ... 179 185 196]
 [170 169 169 ... 179 186 197]]
Previous Frame
[[168 168 165 ... 171 170 170]
 [169 168 168 ... 170 170 170]
 [176 169 168 ... 170 170 170]
 ...
 [169 168 168 ... 178 182 190]
 [168 170 170 ... 179 185 196]
 [170 169 169 ... 179 186 197]]
Difference of Frames
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
198045 non-changed pixels and 26947 changed pixels
Current Frame
[[168 168 165 ... 171 170 170]
 [169 168 168 ... 170 170 170]
 [176 169 168 ... 170 170 170]
 ...
 [169 168 168 ... 178 182 190]
 [168 170 170 ... 179 185 196]
 [170 169 169 ... 179 186 197]]
Previous Frame
[[168 168 165 ... 171 170 170]
 [169 168 169 ... 170 170 170]
 [176 169 168 ... 170 170 170]
 ...
 [169 168 168 ... 178 182 

210129 non-changed pixels and 14863 changed pixels
Current Frame
[[170 168 168 ... 171 170 170]
 [171 170 170 ... 170 170 170]
 [176 170 169 ... 170 170 170]
 ...
 [169 168 168 ... 178 185 193]
 [169 170 170 ... 181 190 192]
 [170 170 170 ... 181 191 193]]
Previous Frame
[[170 168 168 ... 171 170 170]
 [171 170 169 ... 170 170 170]
 [176 170 171 ... 170 170 170]
 ...
 [169 168 168 ... 178 182 192]
 [169 170 170 ... 179 187 194]
 [170 170 170 ... 179 188 195]]
Difference of Frames
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 254 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 254]
 [  0   0   0 ...   0   0 254]]
192374 non-changed pixels and 32618 changed pixels
Current Frame
[[170 168 168 ... 171 170 170]
 [171 170 170 ... 170 170 170]
 [176 170 167 ... 169 169 170]
 ...
 [169 168 168 ... 178 184 193]
 [169 170 170 ... 180 189 193]
 [170 170 170 ... 180 190 194]]
Previous Frame
[[170 168 168 ... 171 170 170]
 [171 170 170 ... 17

# 